CmulWebPage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls'))
]

website/urls.py
from django.urls import path
from . import views

app_name = "website"

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('evolucao/', views.evolucao, name='evolucao'),
    path('tecnologia/', views.tecnologia, name='tecnologia'),
    path('bussiness_models/', views.bussiness_models, name='bussiness_models'),
    path('interfaces/', views.interfaces, name='interfaces'),
    path('impactos_sociais/', views.impactos_sociais, name='impactos_sociais'),
    path('impactos_eticos/', views.impactos_eticos, name='impactos_eticos'),
    path('portugal/', views.portugal, name='portugal'),
    path('futuro/', views.futuro, name='futuro'),
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, "website/index.html")


def about(request):
    return render(request, "website/about.html")


def evolucao(request):
    return render(request, "website/evolucao.html")


def tecnologia(request):
    return render(request, "website/tecnologia.html")


def bussiness_models(request):
    return render(request, "website/bussiness_Models.html")


def interfaces(request):
    return render(request, "website/interfaces.html")


def impactos_sociais(request):
    return render(request, "website/impactos_sociais.html")


def impactos_eticos(request):
    return render(request, "website/impactos_eticos.html")


def portugal(request):
    return render(request, "website/portugal.html")


def futuro(request):
    return render(request, "website/futuro.html")

website/templates/website/about.html
{% extends 'website/layout.html' %}

{% block main %}
    <style>
        .avatar {
            border-radius: 50%;
            display: block;
            margin-left: auto;
            margin-right: auto;
        }
    </style>
    <div class="col-md-8">
        <h2>Sobre este website</h2>
        <p>Website desenvolvido em Django no âmbito da Disciplina de Comunicação Multimédia.</p>
        <p>Doncente responsável: Professor Fernando Pereira</p>
    </div>
    <div class="col-md-4">
        {% load static %}
        <img src=" {% static 'website/images/IST_logo.png' %}" alt="IST Logo" width="100%" height="90%">
    </div>
    <div class="col-md-12">
        <hr>
        <h1>Website realizado por:</h1>
    </div>
    <div class="col-md-4">
        {% load static %}
        <img src=" {% static 'website/images/Ana.jpeg' %}" alt="" class="avatar" width="50%" height="60%" }>
        <h2 style="text-align: center">Ana Rita Ramalho</h2>
        <h3 style="text-align: center">98466</h3>
    </div>
    <div class="col-md-4">
        {% load static %}
        <img src=" {% static 'website/images/FC.jpeg' %}" alt="" class="avatar" width="50%" height="60%" }>
        <h2 style="text-align: center">Felícia Cruz</h2>
        <h3 style="text-align: center">93987</h3>
    </div>
    <div class="col-md-4">
        {% load static %}
        <img src=" {% static 'website/images/RS.png' %}" alt="" class="avatar" width="50%" height="60%" }>
        <h2 style="text-align: center">Ricardo Santos</h2>
        <h3 style="text-align: center">102217</h3>
    </div>
{% endblock main %}
      

website/templates/website/bussiness_Models.html
{% extends 'website/layout.html' %}

{% block main %}
    <style>
        .image {
            display: block;
            margin-left: auto;
            margin-right: auto;
        }

        .avatar {
            border-radius: 50%;
            display: block;
            margin-left: auto;
            margin-right: auto;
        }
    </style>
    <div class="col-md-12">
        <h2>Modelos de Negócio</h2>
        <p style="text-align: justify">Os três tipos de modelos de negócio presentes nas redes sociais estão
            representados na imagem abaixo.</p>
    </div>
    <div class="col-md-12" style="padding-top: 10px">
        {% load static %}
        <img src=" {% static 'website/images/ModelosDeNegocio.png' %}" alt="" class="image">
    </div>

    <div class="col-md-4" style="padding-top: 20px">
        <h3 style="text-align: center">O modelo Gratuito</h3>
        <p style="text-align: justify">No modelo de negócio gratuito o rendimento resulta de publicidade (anúncios,
            sugestões) direcionada a um
            público-alvo.</p>
    </div>
    <div class="col-md-4" style="padding-top: 20px">
        <h3 style="text-align: center">O modelo Freemium</h3>
        <p style="text-align: justify">O modelo freemium consiste na combinação do modelo gratuito com o pago. Neste
            caso, a utilização é gratuita,
            mas
            algumas funcionalidades requerem subscrição.</p>
    </div>
    <div class="col-md-4" style="padding-top: 20px">
        <h3 style="text-align: center">O modelo Pago</h3>
        <p style="text-align: justify">No modelo pago recorre-se a remunerações periódicas (subscrições
            mensais ou anuais). Neste caso, as subscrições dispõem de algumas vantagens, como por exemplo a remoção de
            anúncios.</p>
    </div>
    <div class="col-md-12">
        <hr>
        <h2>Comparação entre duas redes sociais</h2>
    </div>

    <div class="col-md-6" style="padding-top: 20px">
        {% load static %}
        <img src=" {% static 'website/images/facebook.png' %}" alt="" class="avatar" width="20%" height="55%" }>
        <h3 style="text-align: center">Facebook</h3>
    </div>
    <div class="col-md-6" style="padding-top: 20px">
        {% load static %}
        <img src=" {% static 'website/images/youtube.png' %}" alt="" class="avatar" width="20%" height="55%" }>
        <h3 style="text-align: center">Youtube</h3>
    </div>
    <div class="col-md-6">
        <p style="text-align: justify">Atualmente, o Facebook utiliza o modelo de negócio gratuito.</p>
        <p style="text-align: justify">Contudo, nos primeiros tempos, o modelo adotado tinha como finalidade a
            monetização da plataforma, o qual
            associava o número de utilizadores a um determinado lucro.</p>
        <p style="text-align: justify">
            Hoje, o método lucrativo é baseado na relação utilizador-marca, ou seja,
            o conteúdo apresentado provém da
            análise de influência e do perfil do utilizador.
        </p>
    </div>
    <div class="col-md-6">
        <p style="text-align: justify">A aplicação Youtube utiliza o modelo de negócio gratuito.</p>
        <p style="text-align: justify">
            Recentemente, foi introduzido o modelo pago, apesar de este representar apenas uma pequena parte do lucro
            total. Este último é utilizado pelo Youtube Premium.
        </p>
        <p style="text-align: justify">A maior fonte de rendimento é obtida através de anúncios e publicidade
            direcionada a um público-alvo.
            Normalmente, os anúncios surgem antes, durante e após a apresentação do vídeo.</p>
    </div>
    <div class="col-md-12" style="padding-top: 20px; text-align: center">
        <hr>
        <h2>How Facebook remains free</h2>
        <p></p>
        <iframe width="420" height="315"
                src="https://www.youtube.com/embed/n2H8wx1aBiQ">
        </iframe>
    </div>

{% endblock main %}

website/templates/website/evolucao.html
{% extends 'website/layout.html' %}

{% block main %}
    <div class="col-md-12">
        <h2>Evolução</h2>
        <p>A evolução das redes sociais deriva da capacidade de satisfazer em tempo real as exigências dos
            utilizadores. </p>
        <p>Na imagem abaixo é possível observar o aparecimento e evolução das redes sociais.</p>
    </div>
    <div class="col-md-12" style="padding-top: 10px">
        {% load static %}
        <img src=" {% static 'website/images/evolution.png' %}" alt="" class="image" width="100%" height="100%">
    </div>
{% endblock main %}

website/templates/website/futuro.html
{% extends 'website/layout.html' %}

{% block main %}
    <style>
        .image {
            display: block;
            margin-left: auto;
            margin-right: auto;
        }
    </style>
    <div class="col-md-12">
        <h2>O Futuro...</h2>
        <p>Niguém sabe o que o futuro nos pode trazer mas, temos algumas previsões...</p>
    </div>
    <div class="col-md-4" style="padding-top: 20px;text-align: center">
        <h2>Redes sociais aliadas à realidade virtual?</h2>
    </div>
    <div class="col-md-4" style="padding-top: 20px;text-align: center">
        <h2>Redes sociais aliadas à Inteligência Artificial?</h2>
    </div>
    <div class="col-md-4" style="padding-top: 20px;text-align: center">
        <h2>Redes Sociais aliadas à computação na Nuvem?</h2>
    </div>
    <div class="col-md-4" style="padding-top: 20px">
        {% load static %}
        <img src=" {% static 'website/images/vr.png' %}" alt="" class="image" width="100%" height="90%" }>
    </div>
    <div class="col-md-4" style="padding-top: 20px">
        {% load static %}
        <img src=" {% static 'website/images/IA.png' %}" alt="" class="image" width="100%" height="90%" }>
    </div>
    <div class="col-md-4" style="padding-top: 20px">
        {% load static %}
        <img src=" {% static 'website/images/cloud.png' %}" alt="" class="image" width="100%" height="90%" }>
    </div>
    <div class="col-md-4">
        <p style="text-align: justify">Esta tecnologia tem como objetivo recriar a realidade num ambiente virtual. Desta
            forma, seria interessante
            criar uma rede social que consistisse num mundo virtual com vários utilizadores, por forma a proporcionar
            uma interação próxima da realidade.</p>
    </div>
    <div class="col-md-4">
        <p style="text-align: justify">A combinação entre Inteligência Artificial (IA), redes sociais e multimédia é
            também esperada num futuro próximo. A
            recente evolução nesta área, torna possível a análise do comportamento de cada
            utilizador, assim como permite perceber quais os seus conteúdos de seleção.
        </p>
        <p style="text-align: justify">Para além destes aspetos, a IA permite melhorar fotografias e vídeos, através da
            modificação automática de parâmetros como a luminosidade e/ou o brilho.
        </p>
    </div>
    <div class="col-md-4">
        <p style="text-align: justify">Espera-se também uma combinação entre a multimédia e a computação na nuvem.
            Através
            do processamento de dados na cloud será possível, por exemplo, criar vídeos com resoluções cada vez maiores.
            Contudo, maior resolução dos vídeos exige um hardware mais potente na sua codificação e descodificação. Como
            o hardware disponível nos serviços cloud é muito superior ao que é disponibilizado ao utilizador, este
            problema é facilmente ultrapassado.</p>
    </div>
    <div class="col-md-2" style="padding-top: 20px">
    </div>
    <div class="col-md-4" style="padding-top: 20px;text-align: center">
        <h2>O avanço das redes móveis</h2>
    </div>
    <div class="col-md-4" style="padding-top: 20px;text-align: center">
        <h2>Codecs de vídeo e imagem mais eficientes</h2>
    </div>
    <div class="col-md-2" style="padding-top: 20px">
    </div>
    <div class="col-md-2" style="padding-top: 20px">
    </div>
    <div class="col-md-4" style="padding-top: 20px">
        {% load static %}
        <img src=" {% static 'website/images/5g.png' %}" alt="" class="image" width="100%" height="90%" }>
    </div>
    <div class="col-md-4" style="padding-top: 20px">
        {% load static %}
        <img src=" {% static 'website/images/codecs.png' %}" alt="" class="image" width="100%" height="90%" }>
    </div>
    <div class="col-md-2" style="padding-top: 20px">
    </div>
    <div class="col-md-2" style="padding-top: 20px">
    </div>
    <div class="col-md-4">
        <p style="text-align: justify">O avanço das redes móveis, como o 5G, tem vindo a impulsionar a utilização da
            multimédia nas redes sociais. Esta evolução traduz-se no aumento da velocidade de download e upload,
            tornando possível, por exemplo, a visualização de vídeos com maior resolução em qualquer lugar.</p>
    </div>
    <div class="col-md-4">
        <p style="text-align: justify"> O objetivo desejado é que se atinja uma qualidade transparente utilizando o
            mínimo de largura de banda possível.</p>
        <p style="text-align: justify">Tendo este requisito em conta, novos protocolos de vídeo estão a ser
            desenvolvidos, como o
            Essencial Video Coding (EVC) e o Low Complexity Enhancement Video Coding (LCEVC). Estes prometem ser mais
            eficientes e não ter problemas com o licenciamento, o que não aconteceu com o High Efficiency Video Coding
            (HEVC) e que poderá vir a acontecer com o Versatile Video Coding (VVC), o codec mais recente.
        </p>
        <p style="text-align: justify">Para a fotografia, o codec AV1 Image Format (AVIF), desenvolvido pela Alliance
            For Open Media, poderá
            tornar-se numa futura projeção, uma vez que será relativamente simples de implementar em vários
            dispositivos. </p>
    </div>
    <div class="col-md-2" style="padding-top: 20px">
    </div>
    <div class="col-md-12" style="padding-top: 20px; text-align: center">
        <hr>
        <h2>Facebook Horizon VR Social Media</h2>
        <p></p>
        <iframe width="420" height="315"
                src="https://www.youtube.com/embed/5c44q1XW9p4">
        </iframe>
    </div>
{% endblock main %}

website/templates/website/impactos_eticos.html
{% extends 'website/layout.html' %}

{% block main %}
    <style>
        .image {
            display: block;
            margin-left: auto;
            margin-right: auto;
        }
    </style>
    <div class="col-md-12">
        <h2>Impactos Éticos e Legais</h2>
        <p>A utilização da multimédia nas redes sociais apresenta um conjunto de impactos éticos e legais, sendo a
            violação de direitos de autor (copyright) e a violação da propriedade intelectual, dois exemplos. </p>
    </div>
    <div class="col-md-12">
        <hr>
    </div>
    <div class="col-md-8">
        <h3>Direitos de autor</h3>
        <p style="text-align: justify">Os direitos de autor atribuem proteção legal a um criador de conteúdo.</p>
        <p style="text-align: justify">No caso das redes sociais, a partilha de conteúdo é extremamente fácil, o que faz
            com que a propriedade
            intelectual dos utilizadores seja constantemente invadida. </p>
        <p style="text-align: justify">Um exemplo bastante comum é a utilização de músicas em vídeos no Youtube.</p>
    </div>
    <div class="col-md-4">
        {% load static %}
        <img src=" {% static 'website/images/cp.png' %}" alt="" width="100%" height="100%">
    </div>
    <div class="col-md-12">
        <hr>
    </div>
    <div class="col-md-8">
        <h3>General Data Protection Regulation (GPRD)</h3>
        <p style="text-align: justify">Para tentar mitigar este problema, em 2019, o GPRD tornou ilegal o processamento
            de dados sem o consentimento
            do utilizador.</p>
        <p style="text-align: justify">As rede sociais passaram a ser obrigadas a questionar os utilizadores sobre que
            tipo de dados podem recolher.
            No entanto, o desinteresse pela leitura dos termos de privacidade e utilização das plataformas faz com que
            muitas das vezes sejam partilhados dados privados.</p>
        <p style="text-align: justify">Pode ler mais sobre o GPRD <a
                href="https://ec.europa.eu/info/law/law-topic/data-protection/eu-data-protection-rules_pt"
                target="_blank">aqui.</a></p>
    </div>
    <div class="col-md-4">
        {% load static %}
        <img src=" {% static 'website/images/gprd.png' %}" alt="" width="100%" height="100%">
    </div>
    <div class="col-md-12">
        <hr>
    </div>
    <div class="col-md-8">
        <h3>Privacidade</h3>
        <p style="text-align: justify">A privacidade dos utilizadores nas redes sociais é um tema que tem vindo a ser
            discutido nos últimos
            anos.</p>
        <p style="text-align: justify">O Facebook tem sido o principal alvo de críticas devido ao seu protagonismo.
            Alguns utilizadores começaram a
            deixar de utilizar e confiar nesta rede social. (Notícia completa <a
                    href="https://www.washingtonpost.com/technology/2021/12/22/tech-trust-survey/"
                    target="_blank">aqui</a>)</p>
    </div>
    <div class="col-md-4">
        {% load static %}
        <img src=" {% static 'website/images/lock.gif' %}" class="image" alt="" width="70%" height="100%">
    </div>
    <div class="col-md-12">
        <hr>
    </div>
    <div class="col-md-8">
        <h3>Roubos de identidade e fraude</h3>
        <p style="text-align: justify">Nas redes sociais, a partilha de informação pessoal, como por exemplo, data de
            nascimento, local de residência, endereço de morada, etc, pode trazer consequências.</p>
        <p style="text-align: justify">Devido à facilidade de acesso a este tipo de dados é comum ocorrerem roubos de
            entidade e fraude bancária.</p>
    </div>
    <div class="col-md-4">
        {% load static %}
        <img src=" {% static 'website/images/scam.gif' %}" class="image" alt="" width="70%" height="100%">
    </div>
{% endblock main %}

website/templates/website/impactos_sociais.html
{% extends 'website/layout.html' %}

{% block main %}
    <div class="col-md-8">
        <h2>Impactos Sociais</h2>
        <p style="text-align: justify">A utilização das redes sociais provoca impactos positivos e negativos na
            sociedade. O facto de não existirem
            mecanismos de controlo máximo aplicados aos conteúdos partilhados pelos utilizadores, faz com que este seja
            um tópico bastante polémico.</p>
        <p style="text-align: justify">Os impactos negativos, que tornam os utilizadores “vítimas” das redes sociais,
            refletem um conjunto de
            problemas mentais tais como, ansiedade, isolamento, sedentarismo, desvalorização própria, ciberbullying e
            falta de privacidade. Em situações extremas, estes impactos podem fazer com que muitos utilizadores cometam
            suicídio</p>
    </div>
    <div class="col-md-4">
        {% load static %}
        <img src=" {% static 'website/images/social_impacts.jpg' %}" class="image" alt="" width="70%" height="100%">
    </div>
    <div class="col-md-12">
        <hr>
    </div>
    <div class="col-md-8">
        <h2>Mitigação dos impactos negativos nos mais novos</h2>
        <p style="text-align: justify">Para mitigar os impactos negativos é bastante importante apresentar cuidados
            acrescidos aquando da utilização
            das redes sociais por parte de
            crianças e adolescentes. Isto porque, a supervisão torna-se insuficiente quando o acesso a conteúdos online
            se encontra à distância de um simples click.</p>
        <p style="text-align: justify">O facto da maior parte da interação online ocorrer nestas faixas etárias faz com
            que as mesmas se tornem
            bastante vulneráveis a ciberataques. </p>
        <p style="text-align: justify">A sua ignorância e inocência faz com que sejam expostos a comportamentos menos
            apropriados, influenciando
            negativamente os seus valores.</p>
    </div>
    <div class="col-md-4">
        {% load static %}
        <img src=" {% static 'website/images/kids.jpg' %}" class="image" alt="" width="70%" height="100%">
    </div>
{% endblock main %}

website/templates/website/index.html
{% extends 'website/layout.html' %}
{% block nav-home %}<strong class="nav-active">About</strong>{% endblock %}
{% block main %}
    <div class="col-md-8">
        <h2>Apresentação do nosso projecto</h2>
        <ul>
            <li>
                A evolução &#x2197;
            </li>
            <li>
                A tecnologia &#128190;
            </li>
            <li>
                Os modelos de negócio &#128176;
            </li>
            <li>
                As interfaces &#128241;
            </li>
            <li>
                Os impactos &#9989;
            </li>
            <li>
                Em Portugal {% load static %}
                <img src=" {% static 'website/images/portugal.png' %}" alt="" width="4%" height="3%">
            </li>
            <li>
                O futuro &#128302;
            </li>
        </ul>

    </div>
    <div class="col-md-4">
        {% load static %}
        <img src=" {% static 'website/images/intro.gif' %}" alt="" width="100%" height="100%">
    </div>
    <div class="col-md-12">
        <hr>
        <p style="text-align: justify">Atualmente, a sociedade pretende captar toda a empatia, emoção e sensação do
            mundo através de um simples
            aparelho tecnológico. Desta forma, é necessário que o conjunto de sinais sensoriais, captados através do
            áudio, da imagem e do vídeo, se traduzam numa representação espaciotemporal quase perfeita. O acesso e a
            partilha de informação, independentemente do tipo de conteúdo, levou à criação de espaços virtuais comuns,
            as redes sociais. No entanto, a sua evolução tem vindo a revolucionar a forma como a população cria,
            interage e comunica através da utilização de multimédia nas suas diversas formas.
            O nosso artigo pretende realçar o impacto das redes sociais na produção de conteúdo multimédia e no conjunto
            de
            princípios éticos, legais e culturais que devem ser reconhecidos e que asseguram a integridade da sociedade.
        </p>
    </div>
    <div class="col-md-12">
        <hr>
        <p style="text-align: center">
            <iframe width="1000" height="600"
                    src="https://www.youtube.com/embed/24YO3Tkdvf0">
            </iframe>
        </p>
    </div>
{% endblock main %}

website/templates/website/interfaces.html
{% extends 'website/layout.html' %}

{% block main %}
    <style>
        .image {
            display: block;
            margin-left: auto;
            margin-right: auto;
        }

        .avatar {
            border-radius: 50%;
            display: block;
            margin-left: auto;
            margin-right: auto;
        }
    </style>
    <div class="col-md-12">
        <h2>Interfaces</h2>
        <p style="text-align: justify">As interfaces de utilizador das redes sociais são um factor determinante para o
            seu sucesso. Idealmente, estas devem ser fáceis de utilizar/interpretar e devem possuir um design atrativo,
            por forma a
            captar a atenção do utilizador. Os utilizadores ao navegarem nas diferentes plataformas são submetidos a um
            conjunto de anúncios que vão
            surgindo de forma estratégica. Este método tem como objetivo influenciar e cativar os seus interesses.</p>
        <p style="text-align: justify">Na imagem abaixo encontram-se as interfaces de duas redes sociais populares.</p>
    </div>
    <div class="col-md-12">
        <hr>
        <h2>Comparação entre duas redes sociais</h2>
    </div>
    <div class="col-md-6" style="padding-top: 20px">
        {% load static %}
        <img src=" {% static 'website/images/linkedin.png' %}" alt="" class="avatar" width="20%" height="55%" }>
        <h3 style="text-align: center">Linkedin</h3>
    </div>
    <div class="col-md-6" style="padding-top: 20px">
        {% load static %}
        <img src=" {% static 'website/images/youtube.png' %}" alt="" class="avatar" width="20%" height="55%" }>
        <h3 style="text-align: center">Youtube</h3>
    </div>
    <div class="col-md-6" style="padding-top: 20px">
        {% load static %}
        <img src=" {% static 'website/images/linkedin_ui.png' %}" alt="" class="image" width="100%" height="100%" }>
    </div>
    <div class="col-md-6" style="padding-top: 20px">
        {% load static %}
        <img src=" {% static 'website/images/youtube_ui.png' %}" alt="" class="image" width="100%" height="100%" }>
    </div>

    <div class="col-md-6" style="padding-top: 20px">
        <p style="text-align: center">Utilização intuitiva &#9989;</p>
        <p style="text-align: center">Design atrativo &#9989;</p>
    </div>

    <div class="col-md-6" style="padding-top: 20px">
        <p style="text-align: center">Utilização intuitiva &#9989;</p>
        <p style="text-align: center">Design atrativo &#9989;</p>
    </div>
    <div class="col-md-12" style="padding-top: 20px; text-align: center">
        <hr>
        <h2>UI designs, tips and tricks</h2>
        <p></p>
        <iframe width="420" height="315"
                src="https://www.youtube.com/embed/5rkwYnd--_8">
        </iframe>
    </div>
{% endblock main %}

website/templates/website/layout.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Multimédia nas redes sociais</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/jumbotron/">

    <!-- Bootstrap core CSS
    https://getbootstrap.com/docs/4.0/examples/jumbotron/
    -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <!-- Custom styles for this template -->
    {% load static %}
    <link rel="stylesheet" href=" {% static 'website/styles.css' %} ">

</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #1b1b1b;">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href=" {% url 'website:index' %} ">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=" {% url 'website:evolucao' %} ">Evolução</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=" {% url 'website:tecnologia' %} ">Tecnologia</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=" {% url 'website:bussiness_models' %} ">Modelos de Negócio</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=" {% url 'website:interfaces' %} ">Interfaces</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">Impactos</a>
                <div class="dropdown-menu" aria-labelledby="dropdown03">
                    <a class="dropdown-item" href="{% url 'website:impactos_sociais' %}">Sociais</a>
                    <a class="dropdown-item" href="{% url 'website:impactos_eticos' %}">Éticos e Legais</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=" {% url 'website:portugal' %} ">Em Portugal</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=" {% url 'website:futuro' %} ">O Futuro...</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=" {% url 'website:about' %} ">Sobre</a>
            </li>
        </ul>
    </div>
</nav>

<main role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron" style="padding-bottom: 20px;padding-top: 85px;background-color: deepskyblue">
        <div class="container">
            <h1 class="display-3">Multimédia nas redes sociais</h1>
            <p><i>Comunicação Multimédia</i></p>
        </div>
    </div>

    <div class="container">

        <div class="row">
            {% block main %}

            {% endblock %}
        </div>

    </div>

    <hr>

    </div> <!-- /container -->

</main>

<footer class="container">
    <p>&copy; 2022 Comunicação Multimédia Instituto Superior Técnico 2022</p>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="../../assets/js/vendor/popper.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
</body>
</html>